/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import crud.crud;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
    crud mycode;

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        mycode= new crud();
        mycode.tampilDataKlien(tabelKlien, "SELECT*FROM klien");
        mycode.tampilDataBarang(tabelBarang, "SELECT*FROM barang");
        mycode.tampilDataPO(tabelPO, "SELECT*FROM purchase_order");
        mycode.tampilDataInvoice(tabelInvoice, "SELECT*FROM invoice");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlPO = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtTglPO = new javax.swing.JTextField();
        txtNoPO = new javax.swing.JTextField();
        txtIdKlienPO = new javax.swing.JTextField();
        btnHpsPO = new javax.swing.JButton();
        btnSmpnPo = new javax.swing.JButton();
        btnUbhPO = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtIdBrgPO = new javax.swing.JTextField();
        txtStsPO = new javax.swing.JTextField();
        txtQtyPO = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtHrgPO = new javax.swing.JTextField();
        txtUoM = new javax.swing.JTextField();
        txtCariPO = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelPO = new javax.swing.JTable();
        pnlKlien = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaKlien = new javax.swing.JTextField();
        txtIdKlien = new javax.swing.JTextField();
        txtTelpKlien = new javax.swing.JTextField();
        txtAlamatKlien = new javax.swing.JTextField();
        txtCariKlien = new javax.swing.JTextField();
        txtKodePosKlien = new javax.swing.JTextField();
        btnHpsKln = new javax.swing.JButton();
        btnSmpnKln = new javax.swing.JButton();
        btnUbhKln = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKlien = new javax.swing.JTable();
        txtStatusKlien = new javax.swing.JTextField();
        pnlBarang = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        txtIdBarang = new javax.swing.JTextField();
        txtHargaSatuan = new javax.swing.JTextField();
        txtSpesifikasi = new javax.swing.JTextField();
        txtCariBarang = new javax.swing.JTextField();
        btnHpsBrg = new javax.swing.JButton();
        btnSmpnBrg = new javax.swing.JButton();
        btnUbhBrg = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        pnlInvoice = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNoPoInv = new javax.swing.JTextField();
        txtNoInvoice = new javax.swing.JTextField();
        txtTglJthTempo = new javax.swing.JTextField();
        txtTglInvoice = new javax.swing.JTextField();
        txtCariInvoice = new javax.swing.JTextField();
        btnHpsInv = new javax.swing.JButton();
        btnSmpnInv = new javax.swing.JButton();
        btnUbhInv = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelInvoice = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtTotalTagihan = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnKlien = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnPO = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnInvoice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        Content.add(pnlHome, "card6");

        pnlPO.setBackground(new java.awt.Color(204, 204, 204));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("ID Klien");

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Tanggal");

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("No PO");

        txtTglPO.setBackground(new java.awt.Color(255, 255, 255));
        txtTglPO.setForeground(new java.awt.Color(0, 0, 0));

        txtNoPO.setBackground(new java.awt.Color(255, 255, 255));
        txtNoPO.setForeground(new java.awt.Color(0, 0, 0));

        txtIdKlienPO.setBackground(new java.awt.Color(255, 255, 255));
        txtIdKlienPO.setForeground(new java.awt.Color(0, 0, 0));

        btnHpsPO.setText("HAPUS");
        btnHpsPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsPOActionPerformed(evt);
            }
        });

        btnSmpnPo.setText("SIMPAN");
        btnSmpnPo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnPoActionPerformed(evt);
            }
        });

        btnUbhPO.setText("UBAH");
        btnUbhPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhPOActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Satuan");

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("ID Barang");

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Status");

        txtIdBrgPO.setBackground(new java.awt.Color(255, 255, 255));
        txtIdBrgPO.setForeground(new java.awt.Color(0, 0, 0));

        txtStsPO.setBackground(new java.awt.Color(255, 255, 255));
        txtStsPO.setForeground(new java.awt.Color(0, 0, 0));

        txtQtyPO.setBackground(new java.awt.Color(255, 255, 255));
        txtQtyPO.setForeground(new java.awt.Color(0, 0, 0));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("UoM");

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Harga");

        txtHrgPO.setBackground(new java.awt.Color(255, 255, 255));
        txtHrgPO.setForeground(new java.awt.Color(0, 0, 0));

        txtUoM.setBackground(new java.awt.Color(255, 255, 255));
        txtUoM.setForeground(new java.awt.Color(0, 0, 0));

        txtCariPO.setBackground(new java.awt.Color(255, 255, 255));
        txtCariPO.setForeground(new java.awt.Color(0, 0, 0));
        txtCariPO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPOKeyReleased(evt);
            }
        });

        tabelPO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelPO);

        javax.swing.GroupLayout pnlPOLayout = new javax.swing.GroupLayout(pnlPO);
        pnlPO.setLayout(pnlPOLayout);
        pnlPOLayout.setHorizontalGroup(
            pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPOLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPOLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(89, 89, 89)
                        .addComponent(txtNoPO, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSmpnPo))
                    .addGroup(pnlPOLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(75, 75, 75)
                        .addComponent(txtTglPO, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnUbhPO))
                    .addGroup(pnlPOLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(87, 87, 87)
                        .addComponent(txtStsPO, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPOLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(61, 61, 61)
                        .addComponent(txtIdBrgPO, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPOLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(83, 83, 83)
                        .addComponent(txtQtyPO, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPOLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(91, 91, 91)
                        .addComponent(txtHrgPO, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPOLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(103, 103, 103)
                        .addComponent(txtUoM, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCariPO, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPOLayout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(78, 78, 78)
                            .addComponent(txtIdKlienPO, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnHpsPO))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pnlPOLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHpsPO, btnSmpnPo, btnUbhPO});

        pnlPOLayout.setVerticalGroup(
            pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(txtNoPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSmpnPo))
                .addGap(13, 13, 13)
                .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(txtTglPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbhPO))
                .addGap(13, 13, 13)
                .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txtIdKlienPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsPO))
                .addGap(13, 13, 13)
                .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(txtStsPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(txtIdBrgPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(txtQtyPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(txtHrgPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(txtUoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(txtCariPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Content.add(pnlPO, "card4");

        pnlKlien.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Status");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Kode Pos");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telpon");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Alamat");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Klien");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID Klien");

        txtNamaKlien.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaKlien.setForeground(new java.awt.Color(0, 0, 0));

        txtIdKlien.setBackground(new java.awt.Color(255, 255, 255));
        txtIdKlien.setForeground(new java.awt.Color(0, 0, 0));

        txtTelpKlien.setBackground(new java.awt.Color(255, 255, 255));
        txtTelpKlien.setForeground(new java.awt.Color(0, 0, 0));

        txtAlamatKlien.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamatKlien.setForeground(new java.awt.Color(0, 0, 0));

        txtCariKlien.setBackground(new java.awt.Color(255, 255, 255));
        txtCariKlien.setForeground(new java.awt.Color(0, 0, 0));
        txtCariKlien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKlienKeyReleased(evt);
            }
        });

        txtKodePosKlien.setBackground(new java.awt.Color(255, 255, 255));
        txtKodePosKlien.setForeground(new java.awt.Color(0, 0, 0));

        btnHpsKln.setText("HAPUS");
        btnHpsKln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsKlnActionPerformed(evt);
            }
        });

        btnSmpnKln.setText("SIMPAN");
        btnSmpnKln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnKlnActionPerformed(evt);
            }
        });

        btnUbhKln.setText("UBAH");
        btnUbhKln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhKlnActionPerformed(evt);
            }
        });

        tabelKlien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelKlien);

        txtStatusKlien.setBackground(new java.awt.Color(255, 255, 255));
        txtStatusKlien.setForeground(new java.awt.Color(0, 0, 0));
        txtStatusKlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusKlienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKlienLayout = new javax.swing.GroupLayout(pnlKlien);
        pnlKlien.setLayout(pnlKlienLayout);
        pnlKlienLayout.setHorizontalGroup(
            pnlKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKlienLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(pnlKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlKlienLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(78, 78, 78)
                        .addComponent(txtIdKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSmpnKln, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKlienLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(47, 47, 47)
                        .addComponent(txtNamaKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnUbhKln))
                    .addGroup(pnlKlienLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(82, 82, 82)
                        .addComponent(txtAlamatKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnHpsKln))
                    .addGroup(pnlKlienLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(85, 85, 85)
                        .addComponent(txtTelpKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKlienLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(64, 64, 64)
                        .addComponent(txtKodePosKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKlienLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(87, 87, 87)
                        .addComponent(txtStatusKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCariKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pnlKlienLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHpsKln, btnSmpnKln, btnUbhKln});

        pnlKlienLayout.setVerticalGroup(
            pnlKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKlienLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(pnlKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtIdKlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSmpnKln))
                .addGap(13, 13, 13)
                .addGroup(pnlKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaKlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbhKln))
                .addGap(13, 13, 13)
                .addGroup(pnlKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtAlamatKlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsKln))
                .addGap(13, 13, 13)
                .addGroup(pnlKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtTelpKlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtKodePosKlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlKlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtStatusKlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(txtCariKlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pnlKlienLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHpsKln, btnSmpnKln, btnUbhKln});

        Content.add(pnlKlien, "card3");

        pnlBarang.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Harga Satuan");

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Spesifikasi");

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nama Barang");

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("ID Barang");

        txtNamaBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaBarang.setForeground(new java.awt.Color(0, 0, 0));

        txtIdBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtIdBarang.setForeground(new java.awt.Color(0, 0, 0));

        txtHargaSatuan.setBackground(new java.awt.Color(255, 255, 255));
        txtHargaSatuan.setForeground(new java.awt.Color(0, 0, 0));

        txtSpesifikasi.setBackground(new java.awt.Color(255, 255, 255));
        txtSpesifikasi.setForeground(new java.awt.Color(0, 0, 0));

        txtCariBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtCariBarang.setForeground(new java.awt.Color(0, 0, 0));
        txtCariBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariBarangKeyReleased(evt);
            }
        });

        btnHpsBrg.setText("HAPUS");
        btnHpsBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsBrgActionPerformed(evt);
            }
        });

        btnSmpnBrg.setText("SIMPAN");
        btnSmpnBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnBrgActionPerformed(evt);
            }
        });

        btnUbhBrg.setText("UBAH");
        btnUbhBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhBrgActionPerformed(evt);
            }
        });

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelBarang);

        javax.swing.GroupLayout pnlBarangLayout = new javax.swing.GroupLayout(pnlBarang);
        pnlBarang.setLayout(pnlBarangLayout);
        pnlBarangLayout.setHorizontalGroup(
            pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarangLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBarangLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(61, 61, 61)
                        .addComponent(txtIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSmpnBrg))
                    .addGroup(pnlBarangLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(29, 29, 29)
                        .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnUbhBrg))
                    .addGroup(pnlBarangLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(51, 51, 51)
                        .addComponent(txtSpesifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnHpsBrg))
                    .addGroup(pnlBarangLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(29, 29, 29)
                        .addComponent(txtHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pnlBarangLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHpsBrg, btnSmpnBrg, btnUbhBrg});

        pnlBarangLayout.setVerticalGroup(
            pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarangLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSmpnBrg))
                .addGap(13, 13, 13)
                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbhBrg))
                .addGap(13, 13, 13)
                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtSpesifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsBrg))
                .addGap(13, 13, 13)
                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(txtCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        Content.add(pnlBarang, "card5");

        pnlInvoice.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Jatuh Tempo");

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Tanggal Invoice");

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("No PO");

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("No Invoice");

        txtNoPoInv.setBackground(new java.awt.Color(255, 255, 255));
        txtNoPoInv.setForeground(new java.awt.Color(0, 0, 0));

        txtNoInvoice.setBackground(new java.awt.Color(255, 255, 255));
        txtNoInvoice.setForeground(new java.awt.Color(0, 0, 0));

        txtTglJthTempo.setBackground(new java.awt.Color(255, 255, 255));
        txtTglJthTempo.setForeground(new java.awt.Color(0, 0, 0));

        txtTglInvoice.setBackground(new java.awt.Color(255, 255, 255));
        txtTglInvoice.setForeground(new java.awt.Color(0, 0, 0));

        txtCariInvoice.setBackground(new java.awt.Color(255, 255, 255));
        txtCariInvoice.setForeground(new java.awt.Color(0, 0, 0));
        txtCariInvoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariInvoiceKeyReleased(evt);
            }
        });

        btnHpsInv.setText("HAPUS");
        btnHpsInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsInvActionPerformed(evt);
            }
        });

        btnSmpnInv.setText("SIMPAN");
        btnSmpnInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnInvActionPerformed(evt);
            }
        });

        btnUbhInv.setText("UBAH");
        btnUbhInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhInvActionPerformed(evt);
            }
        });

        tabelInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelInvoice);

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Total Tagihan");

        txtTotalTagihan.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalTagihan.setForeground(new java.awt.Color(0, 0, 0));

        txtDiskon.setBackground(new java.awt.Color(255, 255, 255));
        txtDiskon.setForeground(new java.awt.Color(0, 0, 0));

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Diskon");

        javax.swing.GroupLayout pnlInvoiceLayout = new javax.swing.GroupLayout(pnlInvoice);
        pnlInvoice.setLayout(pnlInvoiceLayout);
        pnlInvoiceLayout.setHorizontalGroup(
            pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoiceLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInvoiceLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(55, 55, 55)
                        .addComponent(txtNoInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSmpnInv))
                    .addGroup(pnlInvoiceLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(89, 89, 89)
                        .addComponent(txtNoPoInv, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnUbhInv))
                    .addGroup(pnlInvoiceLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(33, 33, 33)
                        .addComponent(txtTglJthTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInvoiceLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(85, 85, 85)
                        .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInvoiceLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(29, 29, 29)
                        .addComponent(txtTotalTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCariInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlInvoiceLayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(12, 12, 12)
                            .addComponent(txtTglInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnHpsInv))))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pnlInvoiceLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHpsInv, btnSmpnInv, btnUbhInv});

        pnlInvoiceLayout.setVerticalGroup(
            pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoiceLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtNoInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSmpnInv))
                .addGap(13, 13, 13)
                .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtNoPoInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbhInv))
                .addGap(13, 13, 13)
                .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtTglInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsInv))
                .addGap(13, 13, 13)
                .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtTglJthTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txtTotalTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(txtCariInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        Content.add(pnlInvoice, "card5");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM INFORMASI TAMBANG");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(51, 51, 51));
        Menu.setForeground(new java.awt.Color(0, 0, 0));

        btnKlien.setBackground(new java.awt.Color(204, 204, 204));
        btnKlien.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKlien.setForeground(new java.awt.Color(0, 0, 0));
        btnKlien.setText("KLIEN");
        btnKlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlienActionPerformed(evt);
            }
        });

        btnBarang.setBackground(new java.awt.Color(204, 204, 204));
        btnBarang.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnBarang.setForeground(new java.awt.Color(0, 0, 0));
        btnBarang.setText("BARANG");
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });

        btnPO.setBackground(new java.awt.Color(204, 204, 204));
        btnPO.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPO.setForeground(new java.awt.Color(0, 0, 0));
        btnPO.setText("PURCHASE ORDER");
        btnPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPOActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(204, 204, 204));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnInvoice.setBackground(new java.awt.Color(204, 204, 204));
        btnInvoice.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnInvoice.setForeground(new java.awt.Color(0, 0, 0));
        btnInvoice.setText("INVOICE");
        btnInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBarang)
                    .addComponent(btnKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPO)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInvoice)))
                .addContainerGap())
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBarang, btnInvoice, btnKlien, btnPO});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBarang)
                .addGap(18, 18, 18)
                .addComponent(btnPO)
                .addGap(18, 18, 18)
                .addComponent(btnInvoice)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBarang, btnInvoice, btnKlien, btnPO});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnKlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlienActionPerformed
        Content.removeAll(); 
        Content.add(pnlKlien);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnKlienActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        Content.removeAll(); 
        Content.add(pnlBarang);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPOActionPerformed
        Content.removeAll(); 
        Content.add(pnlPO);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnPOActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceActionPerformed
        Content.removeAll(); 
        Content.add(pnlInvoice);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnInvoiceActionPerformed

    private void txtStatusKlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusKlienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusKlienActionPerformed

    private void btnSmpnKlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnKlnActionPerformed
        try {
            if(txtIdKlien.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Klien Belum Diisi");
                txtIdKlien.requestFocus();
            } else if(txtNamaKlien.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Klien Belum Diisi");
                txtNamaKlien.requestFocus();
            } else if(txtAlamatKlien.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Alamat Belum Diisi");
                txtAlamatKlien.requestFocus();
            } else if(txtTelpKlien.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No Telepon Belum Diisi");
                txtTelpKlien.requestFocus();
            } else if(txtKodePosKlien.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Kode Pos Belum Diisi");
                txtKodePosKlien.requestFocus();
            } else if(txtStatusKlien.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Status Belum Diisi");
                txtStatusKlien.requestFocus();
            } else {
                mycode.simpanKlien02(txtIdKlien.getText(), txtNamaKlien.getText(), txtAlamatKlien.getText(), 
                                    txtTelpKlien.getText(), txtKodePosKlien.getText(), txtStatusKlien.getText());

                mycode.tampilDataKlien(tabelKlien, "SELECT*FROM klien");

                if (mycode.duplikasi==true){
                    txtNamaKlien.setText(mycode.CEK_NAMA_KLIEN);
                    txtAlamatKlien.setText(mycode.CEK_ALAMAT);
                    txtTelpKlien.setText(mycode.CEK_TELP_KLIEN);
                    txtKodePosKlien.setText(mycode.CEK_KODEPOS);
                    txtStatusKlien.setText(mycode.CEK_STATUS_KLIEN);
                }
            }
        } catch (Exception e) {            
        }
    }//GEN-LAST:event_btnSmpnKlnActionPerformed

    private void btnUbhKlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhKlnActionPerformed
        try {
            mycode.ubahKlien(txtIdKlien.getText(), txtNamaKlien.getText(), txtAlamatKlien.getText(), 
                             txtTelpKlien.getText(), txtKodePosKlien.getText(), txtStatusKlien.getText());
            mycode.tampilDataKlien(tabelKlien, "SELECT*FROM klien"); 
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnUbhKlnActionPerformed

    private void btnHpsKlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsKlnActionPerformed
        try {
            mycode.hapusKlien(txtIdKlien.getText());
            mycode.tampilDataKlien(tabelKlien, "SELECT*FROM klien");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsKlnActionPerformed

    private void txtCariKlienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKlienKeyReleased
        String c = txtCariKlien.getText();
        String cari = "SELECT*FROM klien WHERE id_klien LIKE '%"+c+"%'"+
                      "or nama_klien LIKE '%"+c+"%' or alamat LIKE '%"+c+"%' or telp LIKE '%"+c+"%'"+
                      "or kodepos LIKE '%"+c+"%' or status LIKE '%"+c+"%'";
        mycode.tampilDataKlien(tabelKlien, cari);
    }//GEN-LAST:event_txtCariKlienKeyReleased

    private void btnUbhBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhBrgActionPerformed
        try {
                mycode.ubahBarang(txtIdBarang.getText(), txtNamaBarang.getText(), 
                                  txtSpesifikasi.getText(), txtHargaSatuan.getText());

                // Refresh tabel (menyesuaikan dengan pola hapus)
                mycode.tampilDataBarang(tabelBarang, "SELECT*FROM barang"); 
            } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhBrgActionPerformed

    private void btnSmpnBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnBrgActionPerformed
        try {
            if(txtIdBarang.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Barang Belum Diisi");
                txtIdBarang.requestFocus();
            } else if(txtNamaBarang.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Barang Belum Diisi");
                txtNamaBarang.requestFocus();
            } else if(txtSpesifikasi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Spesifikasi Belum Diisi");
                txtSpesifikasi.requestFocus();
            } else if(txtHargaSatuan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Harga Satuan Belum Diisi");
                txtHargaSatuan.requestFocus();
            } else {
                mycode.simpanBarang02(txtIdBarang.getText(), txtNamaBarang.getText(), 
                                     txtSpesifikasi.getText(), txtHargaSatuan.getText());
                mycode.tampilDataBarang(tabelBarang, "SELECT*FROM Barang");

                if (mycode.duplikasi == true){
                    txtNamaBarang.setText(mycode.CEK_NAMA_BARANG);
                    txtSpesifikasi.setText(mycode.CEK_SPESIFIKASI);
                    txtHargaSatuan.setText(mycode.CEK_HARGA_SATUAN);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnBrgActionPerformed

    private void btnHpsBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsBrgActionPerformed
        try {
            mycode.hapusBarang(txtIdBarang.getText());
            mycode.tampilDataBarang(tabelBarang, "SELECT*FROM Barang ");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsBrgActionPerformed

    private void txtCariBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariBarangKeyReleased
        String c = txtCariBarang.getText();
        String cari = "SELECT*FROM Barang WHERE id_barang LIKE '%"+c+"%'"+
                      "OR nama_barang LIKE '%"+c+"%' OR spesifikasi LIKE '%"+c+"%'"+
                      "OR harga_satuan LIKE '%"+c+"%'";
        mycode.tampilDataBarang(tabelBarang, cari);
    }//GEN-LAST:event_txtCariBarangKeyReleased

    private void txtCariInvoiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariInvoiceKeyReleased
        String c = txtCariInvoice.getText();
        String cari = "SELECT*FROM invoice WHERE no_invoice LIKE '%"+c+"%'"+
                      "OR no_po LIKE '%"+c+"%' OR tgl_invoice LIKE '%"+c+"%'"+
                      "OR tgl_jth_tempo LIKE '%"+c+"%' OR diskon LIKE '%"+c+"%'"+
                      "OR total_tagihan LIKE '%"+c+"%'";
        mycode.tampilDataInvoice(tabelInvoice, cari);
    }//GEN-LAST:event_txtCariInvoiceKeyReleased

    private void btnHpsInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsInvActionPerformed
        try {
            mycode.hapusInvoice(txtNoInvoice.getText());
            mycode.tampilDataInvoice(tabelInvoice, "SELECT*FROM invoice");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsInvActionPerformed

    private void btnSmpnInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnInvActionPerformed
        try {
            if(txtNoInvoice.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No Invoice Belum Diisi");
                txtNoInvoice.requestFocus();
            } else if(txtNoPoInv.getText().isEmpty()){ // Asumsi nama beda
                JOptionPane.showMessageDialog(null, "No PO Belum Diisi");
                txtNoPoInv.requestFocus();
            } else if(txtTglInvoice.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tgl Invoice Belum Diisi");
                txtTglInvoice.requestFocus();
            } else if(txtTglJthTempo.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tgl Jatuh Tempo Belum Diisi");
                txtTglJthTempo.requestFocus();
            } else if(txtDiskon.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Diskon Belum Diisi");
                txtDiskon.requestFocus();
            } else if(txtTotalTagihan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Total Tagihan Belum Diisi");
                txtTotalTagihan.requestFocus();
            } else {
                mycode.simpanInvoice02(txtNoInvoice.getText(), txtNoPoInv.getText(), 
                                       txtTglInvoice.getText(), txtTglJthTempo.getText(), 
                                       txtDiskon.getText(), txtTotalTagihan.getText());

                // Refresh tabel
                mycode.tampilDataInvoice(tabelInvoice, "SELECT*FROM invoice");

                // Cek duplikasi (sesuai pola Anda)
                if (mycode.duplikasi == true){
                    txtNoPoInv.setText(mycode.CEK_NO_PO);
                    txtTglInvoice.setText(mycode.CEK_TGL_INVOICE);
                    txtTglJthTempo.setText(mycode.CEK_JTH_TEMPO);
                    txtDiskon.setText(mycode.CEK_DISKON);
                    txtTotalTagihan.setText(mycode.CEK_TOTAL_TAGIHAN);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnInvActionPerformed

    private void btnUbhInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhInvActionPerformed
        try {
            mycode.ubahInvoice(txtNoInvoice.getText(), txtNoPoInv.getText(), 
                               txtTglInvoice.getText(), txtTglJthTempo.getText(), 
                               txtDiskon.getText(), txtTotalTagihan.getText());

            // Refresh tabel
            mycode.tampilDataInvoice(tabelInvoice, "SELECT*FROM invoice");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhInvActionPerformed

    private void btnHpsPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsPOActionPerformed
        try {
            mycode.hapusPO(txtNoPO.getText());
            mycode.tampilDataPO(tabelPO, "SELECT*FROM Purchase_Order");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsPOActionPerformed

    private void btnSmpnPoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnPoActionPerformed
        try {
            if(txtNoPO.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No PO Belum Diisi");
                txtNoPO.requestFocus();
            } else if(txtTglPO.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tanggal PO Belum Diisi");
                txtTglPO.requestFocus();
            } else if(txtIdKlienPO.getText().isEmpty()){ // Asumsi nama beda
                JOptionPane.showMessageDialog(null, "ID Klien Belum Diisi");
                txtIdKlienPO.requestFocus();
            } else if(txtStsPO.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Status PO Belum Diisi");
                txtStsPO.requestFocus();
            } else if(txtIdBrgPO.getText().isEmpty()){ // Asumsi nama beda
                JOptionPane.showMessageDialog(null, "ID Barang Belum Diisi");
                txtIdBrgPO.requestFocus();
            } else if(txtQtyPO.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Qty Belum Diisi");
                txtQtyPO.requestFocus();
            } else if(txtHrgPO.getText().isEmpty()){ // Asumsi nama beda
                JOptionPane.showMessageDialog(null, "Harga Belum Diisi");
                txtHrgPO.requestFocus();
            } else if(txtUoM.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "UoM Belum Diisi");
                txtUoM.requestFocus();
            } else {
                mycode.simpanPO02(txtNoPO.getText(), txtTglPO.getText(), txtIdKlienPO.getText(),
                                 txtStsPO.getText(), txtIdBrgPO.getText(), txtQtyPO.getText(),
                                 txtHrgPO.getText(), txtUoM.getText());

                // Refresh tabel
                mycode.tampilDataPO(tabelPO, "SELECT*FROM Purchase_Order");

                // Cek duplikasi (sesuai pola Anda)
                if (mycode.duplikasi == true){
                    txtTglPO.setText(mycode.CEK_TGL_PO);
                    txtIdKlienPO.setText(mycode.CEK_ID_KLIEN);
                    txtStsPO.setText(mycode.CEK_STATUS_PO);
                    txtIdBrgPO.setText(mycode.CEK_ID_BARANG);
                    txtQtyPO.setText(mycode.CEK_QTY);
                    txtHrgPO.setText(mycode.CEK_HARGA_PO);
                    txtUoM.setText(mycode.CEK_UOM);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnPoActionPerformed

    private void btnUbhPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhPOActionPerformed
        try {
            mycode.ubahPO(txtNoPO.getText(), txtTglPO.getText(), txtIdKlienPO.getText(),
                          txtStsPO.getText(), txtIdBrgPO.getText(), txtQtyPO.getText(),
                          txtHrgPO.getText(), txtUoM.getText());

            // Refresh tabel
            mycode.tampilDataPO(tabelPO, "SELECT*FROM Purchase_Order");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhPOActionPerformed

    private void txtCariPOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPOKeyReleased
        String c = txtCariPO.getText();
        String cari = "SELECT*FROM Purchase_Order WHERE no_po LIKE '%"+c+"%'"+
                      "OR tgl_po LIKE '%"+c+"%' OR id_klien LIKE '%"+c+"%'"+
                      "OR status_po LIKE '%"+c+"%' OR id_barang LIKE '%"+c+"%'"+
                      "OR qty LIKE '%"+c+"%' OR harga LIKE '%"+c+"%' OR UoM LIKE '%"+c+"%'";
        mycode.tampilDataPO(tabelPO, cari);
    }//GEN-LAST:event_txtCariPOKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHpsBrg;
    private javax.swing.JButton btnHpsInv;
    private javax.swing.JButton btnHpsKln;
    private javax.swing.JButton btnHpsPO;
    private javax.swing.JButton btnInvoice;
    private javax.swing.JButton btnKlien;
    private javax.swing.JButton btnPO;
    private javax.swing.JButton btnSmpnBrg;
    private javax.swing.JButton btnSmpnInv;
    private javax.swing.JButton btnSmpnKln;
    private javax.swing.JButton btnSmpnPo;
    private javax.swing.JButton btnUbhBrg;
    private javax.swing.JButton btnUbhInv;
    private javax.swing.JButton btnUbhKln;
    private javax.swing.JButton btnUbhPO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnlBarang;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlInvoice;
    private javax.swing.JPanel pnlKlien;
    private javax.swing.JPanel pnlPO;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JTable tabelInvoice;
    private javax.swing.JTable tabelKlien;
    private javax.swing.JTable tabelPO;
    private javax.swing.JTextField txtAlamatKlien;
    private javax.swing.JTextField txtCariBarang;
    private javax.swing.JTextField txtCariInvoice;
    private javax.swing.JTextField txtCariKlien;
    private javax.swing.JTextField txtCariPO;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHargaSatuan;
    private javax.swing.JTextField txtHrgPO;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtIdBrgPO;
    private javax.swing.JTextField txtIdKlien;
    private javax.swing.JTextField txtIdKlienPO;
    private javax.swing.JTextField txtKodePosKlien;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtNamaKlien;
    private javax.swing.JTextField txtNoInvoice;
    private javax.swing.JTextField txtNoPO;
    private javax.swing.JTextField txtNoPoInv;
    private javax.swing.JTextField txtQtyPO;
    private javax.swing.JTextField txtSpesifikasi;
    private javax.swing.JTextField txtStatusKlien;
    private javax.swing.JTextField txtStsPO;
    private javax.swing.JTextField txtTelpKlien;
    private javax.swing.JTextField txtTglInvoice;
    private javax.swing.JTextField txtTglJthTempo;
    private javax.swing.JTextField txtTglPO;
    private javax.swing.JTextField txtTotalTagihan;
    private javax.swing.JTextField txtUoM;
    // End of variables declaration//GEN-END:variables
}
